### ISSUE TITLE
ゲームオーバー処理の実装

### ISSUE THREAD

**Issue by shion-sagawa** [human-osaka-game-2018/Lonely#23]
## 概要
ゲームオーバー処理の追加。

## 背景と目的
敵が存在しているが、ゲームオーバー処理がなかったため。

**Comment by taishi-matsumura** [comment]
description、何か書こう。
こういうのを空っぽのままにする悪癖を直して下さい。

**Comment by shion-sagawa** [comment]
そうですね、これからdescription等に気を付けていきます。
